'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/api/client';
type Catalogue = { sections: { id: string; libelle: string; options: { id: string; libelle: string }[] }[]; matieres: { id: string; libelle: string }[]; annees: { id: string; libelle: string; estActive: boolean }[] };
export default function AcademicPage() {
  const [data, setData] = useState<Catalogue>(); const [message, setMessage] = useState('');
  const refresh = () => api.get<Catalogue>('/administration/catalogue').then((r) => setData(r.data)).catch(() => setMessage('Impossible de charger le catalogue.')); useEffect(() => { void refresh(); }, []);
  async function create(path: string, form: HTMLFormElement) { try { await api.post(`/administration/${path}`, Object.fromEntries(new FormData(form))); form.reset(); setMessage('Enregistré avec succès.'); refresh(); } catch (e: any) { setMessage(e.response?.data?.message?.toString() ?? 'Erreur lors de l’enregistrement.'); } }
  const submit = (path: string) => (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); create(path, e.currentTarget); };
  return <section className="space-y-6"><div><h1 className="text-2xl font-bold">Structure & matières</h1><p className="mt-1 text-slate-600">Configurez les promotions, cours et coefficients.</p></div>{message && <p className="rounded bg-blue-50 p-3 text-sm text-blue-700">{message}</p>}<div className="grid gap-5 lg:grid-cols-2"><Card title="Année scolaire"><form onSubmit={submit('academic-years')} className="flex gap-2"><input required name="libelle" placeholder="2026–2027" className="flex-1 rounded border p-2"/><button className="rounded bg-brand-600 px-3 text-white">Créer</button></form><List values={data?.annees.map((x) => `${x.libelle}${x.estActive ? ' — active' : ''}`)}/></Card><Card title="Section"><form onSubmit={submit('sections')} className="flex gap-2"><input required name="libelle" placeholder="Scientifique" className="flex-1 rounded border p-2"/><button className="rounded bg-brand-600 px-3 text-white">Créer</button></form></Card><Card title="Option"><form onSubmit={submit('options')} className="space-y-2"><input required name="libelle" placeholder="Mathématiques–Physique" className="w-full rounded border p-2"/><select required name="idSection" className="w-full rounded border p-2"><option value="">Section…</option>{data?.sections.map((x) => <option key={x.id} value={x.id}>{x.libelle}</option>)}</select><button className="rounded bg-brand-600 px-3 py-2 text-white">Créer</button></form></Card><Card title="Matière"><form onSubmit={submit('subjects')} className="flex gap-2"><input required name="libelle" placeholder="Mathématiques" className="flex-1 rounded border p-2"/><button className="rounded bg-brand-600 px-3 text-white">Créer</button></form><List values={data?.matieres.map((x) => x.libelle)}/></Card></div></section>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-lg bg-white p-5 shadow-sm"><h2 className="mb-3 font-semibold">{title}</h2>{children}</article>; }
function List({ values }: { values?: string[] }) { return values?.length ? <ul className="mt-3 list-disc pl-5 text-sm text-slate-600">{values.map((x) => <li key={x}>{x}</li>)}</ul> : null; }
